### ISSUE TITLE
启动失败，有个包有问题

### ISSUE THREAD

**Issue by sjq597** [leochen-g/wechaty-web-panel#4]
/root/code/wechat/node_modules/wechaty-puppet-service/dist/cjs/src/client/puppet-service.js:1157
        timestamp ??= 0;
                  ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/root/code/wechat/node_modules/wechaty-puppet-service/dist/cjs/src/mod.js:6:29)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**Comment by leochen-g** [comment]
拉取最新版代码，node>=v16
